### ISSUE TITLE
Question: Where to get information about LEAP protocol?

### ISSUE THREAD

**Issue by hem-bhagat-tark** [thenewwazoo/lutron-leap-js#31]
@thenewwazoo I am trying to implement support for Lutron Radio RA3 in .NET/C# and for that, I am trying to understand LEAP Protocol. In the README of this project, you mentioned that the LEAP protocol is unpublished. I would like to know how you got all the information about the LEAP protocol to write this implementation.

Although I can inspect the code to know the workings of the LEAP protocol and its commands, it will be good to have a document that I can refer to whenever needed. Is there any such document? Or inspecting the code is the only resort? I am not able to find much reference about LEAP protocol on Lutron's Website.

I am specifically interested in how to obtain the Global Certificate (i.e. CA Cert, Cert, and Key placed in the Association.ts file) used for pairing with the Lutron Radio RA3. Although I can directly use them, I would like to know how they are generated to get a better understanding of the workings of the LEAP protocol.

P.S.: I am posting this question as an Issue since there is no dedicated Discussions tab for this repository.

**Comment by thenewwazoo** [comment]
Hi @hem-bhagat-tark, the best other place to look for LEAP information is the [pylutron-caseta](https://github.com/gurumitts/pylutron-caseta) project. That's where I got the keys. I don't have any guess as to where those came from. That's also a much more complete implementation, which will be useful for you to support non-Caseta devices.

I do know that LEAP documentation exists, but I have not read it in order to keep this codebase "pristine", and to avoid potential copyright claims or things of that sort. I'd love it if Lutron would publish it publically, but I'm not the right person to help you find a copy.
